#!/bin/sh
#
# `cmt`: Filter which toggles comments.
#
# Depends: `fmt` (optional)
# Environment: PAGER

: "${PAGER:=more}"

usage () {
	printf '%s\n' \
	'USAGE: cmt [-cChjxX]' \
	'       cmt [-adfFr] [<string>]' \
	'       cmt -b [<string1>] [<string2> [<string3>]]' \
	'       cmt -w [<string1>] [<string2>]' \
	'' \
	'OPTIONS: -h  display this message' \
	'         -a  append: `... <string>'\' \
	'         -b  custom block: `<string2>' \
	'                            <string1> ...' \
	'                            <string3>'\' \
	'         -c  c-style: `/* ... */'\' \
	'         -C  c-style block: `/*' \
	'                              * ...' \
	'                              */'\' \
	'         -d  debug: `... <string> debug'\' \
	'         -H  html: `<!-- ... -->'\' \
	'         -f  formatted (trailing space): `<string> ...'\' \
	'         -F  like `-f'\'', but also pipe through `fmt(1)'\' \
	'         -j  jsdoc: `/**' \
	'                      * ...' \
	'                      */'\' \
	'         -r  returns: `... <string> → '\' \
	'         -w  wrap: `<string1> ... <string2>'\' \
	'         -x  check: `... ✔'\' \
	'         -X  cross: `... ❌'\' \
	| "$PAGER"
	exit
} >&2

main ()
{
	case "$1" in
		-a)	# `append`
			# e.g. `cmt -a $(uni 1f480)`
			# ... 💀
			shift
			line_close=" ${1:-#}"
		;;

		-b)	# `block`
			# e.g. `cmt -b $(uni 1f603) '========'`
			# ========
			# 😃 ...
			# 😃 ...
			# 😃 ...
			# ========
			shift
			save_indent=1
			line_open="${1:-#} "
			block_open="${2:-"$line_open"}"
			block_close="${3:-"$block_open"}"
		;;

		-c)	# `C-style` (single line)
			# /* ... */
			line_open='/* '
			line_close=' */'
		;;

		-C)	# `C-style` (block)
			# /*
			#  * ...
			#  */
			save_indent=1
			block_open='/*'
			line_open=' * '
			block_close=' */'
		;;

		-d)	# `debug`
			# e.g. `cmt -d //`
			# ... // debug
			shift
			line_close=" ${1:-#} debug"
		;;

		-h)
			usage
		;;

		-H)	# `html`
			# <!-- ... -->
			save_indent=1
			line_open='<!-- '
			line_close=' -->'
		;;

		-f)	# `formatted`
			# Adds a trailing space, blank lines are also
			# commented.
			# e.g. `cmt -f \!`
			# ! ...
			# ! ...
			# ! 
			# ! ...
			save_indent=1
			shift
			line_open="${1:-#} "
		;;

		-F)
			# `fully formatted`
			# Like `-f` but also pipe input through `fmt(1)`.
			command -v fmt >/dev/null >&2 || {
				printf 'cmt: `fmt(1)'\'' not found\n'
				return 1
			} >&2
			shift
			exec fmt | cmt -f "${1:-#}"
		;;

		-j)
			# `jsdoc`
			# /**
			#  * ...
			#  */
			save_indent=1
			block_open='/**'
			line_open=' * '
			block_close=' */'
		;;

		-r)
			# `returns`
			# e.g. `cmt -r //`
			# ... // →
			shift
			line_close=" ${1:-#} → "
		;;

		-w)	# `wrap`
			# e.g. `cmt -w "foo" "bar"`
			# foo ... bar
			shift
			save_indent=1
			line_open="${1:-#} "
			line_close=" ${2:-${1:-#}}"
		;;

		-x)	# `check`
			# ... ✔
			save_indent=1
			line_close=' ✔'
		;;

		-X)	# `cross`
			# ... ❌
			save_indent=1
			line_open=' ❌'
		;;

		*)
			# e.g. `cmt //`
			# //...
			line_open="${1:-#}"
		;;
	esac

	while IFS= read -r line; do
		if [ ${i:=1} -eq 1 ]; then
			if [ -z "$line" ]; then
				printf '\n'
				continue
			fi

			i=$((i + 1))

			if [ -n "$save_indent" ]; then
				indent="${line%%[![:space:]]*}"
			fi

			if [ "${line#"$indent"}" = "$block_open" ]; then
				continue
			fi

			if [ -n "$block_open" ]; then
				printf '%s\n' "${indent}${block_open}"
			fi

			if [ -n "$block_close" ]; then
				trap 'printf "%s\n" "${indent}${block_close}"'\
					EXIT
			fi
		fi

		line="${line#"$indent"}"

		case "$line" in
			"")
				# Where formatting is important, comment empty
				# lines.
				if [ -n "$save_indent" ]; then
					line="$line_open"
				else
					printf '\n'
					continue
				fi
			;;

			"$block_close")
				trap - EXIT
				continue
			;;

			"$line_open"*"$line_close")
				line="${line#"$line_open"}"
				line="${line%"$line_close"}"
			;;

			*)
				line="${line_open}${line}${line_close}"
			;;
		esac

		printf '%s\n' "${indent}${line}"
	done
}

main "$@"

